version: '2.1'

services:
  id_contract_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      RPC_HOST: 159.65.197.244
      RPC_PORT: 7545
      SEARCH_CONTRACT: "0x46ae27e520b7ee36a1143eccd9c6ba11b1adb8b2"
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
    networks:
      - backbone
  nginx:
    restart: always
    build: ./nginx
    links:
      - id_contract_api
    # expose:
    #   - 8080
    ports:
      - "8443:8443"
    volumes:
      - ~/cert:/etc/cert
    networks:
      - backbone
networks: 
  backbone:
    driver: bridge
    
