version: '2.1'

services:
  id_contract_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      RPC_HOST: 159.65.197.244
      RPC_PORT: 8545
      SEARCH_CONTRACT: "0x6268cee9aa0624f2bb7bb06c047a9e32a20261e8"
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
    
