openapi: 3.0.0
info:
  description: ''
  version: 0.1.0
  title: Id Contracts API
tags:
  - name: Id Contracts API
    description: ''
paths:
  /contract/deploy:
    post:
      tags:
        - contract
      summary: deploy a new id contract
      description: ''
      operationId: deploy_id_contract
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Id'
        description: Id of entry in identifying DB
        required: true
  /contract/update_id:
    post:
      tags:
        - contract
      summary: set a new id within a contract
      description: ''
      operationId: set_id
      responses:
        '200':
          description: OK
        '400':
          description: Invalid input
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Set'
        description: Current id and new id of entry in indentifying DB
        required: true
  /contract/delete_id:
    post:
      tags:
        - contract
      summary: delete the id from a contract
      description: ''
      operationId: delete_id
      responses:
        '200':
          description: OK
        '400':
          description: Invalid input
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Id'
        description: Current id of entry in identifying DB
        required: true
  /contract/reset_id:
    post:
      tags:
        - contract
      summary: reset id once it has been deleted
      description: ''
      operationId: set_id_after_deletion
      responses:
        '200':
          description: OK
        '400':
          description: Invalid input
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reset'
        description: Id contract address and new id
        required: true
  /contract/get_address:
    get:
      tags:
        - contract
      summary: get id contract address
      description: ''
      operationId: get_id_contract_address
      parameters:
        - in: query
          name: id
          description: Id of entry in identifying DB
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
  /contract/get_identifying_id:
    get:
      tags:
        - contract
      summary: get id stored in id contract
      description: ''
      operationId: get_identifying_id
      parameters:
        - in: query
          name: address
          description: id contract address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authorization error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
  /contract/bulk_get_identifying_id:
    post:
      tags:
        - contract
      summary: get ids stored in id contracts
      description: ''
      operationId: get_identifying_ids
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkGetIds'
        description: Array of addresses
        required: true
  /contract/claim_ownership:
    post:
      tags:
        - contract
      summary: transfer ownership to new address
      description: ''
      operationId: claim_ownership
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimOwnership'
        description: Contract address and new owner's address
        required: true
  /contract/register_third_party:
    post:
      tags:
        - contract
      summary: registers a third party within a given smart contract
      description: ''
      operationId: register_allowed_user
      responses:
        '200':
          description: OK
        '401':
          description: Authorization error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
        description: Contract address and address of party to be registered
        required: true
  /contract/deregister_third_party:
    post:
      tags:
        - contract
      summary: deregisters a third party within a given smart contract
      description: ''
      operationId: deregister_allowed_user
      responses:
        '200':
          description: OK
        '401':
          description: Authorization error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
        description: Contract address and address of party to be deregistered
        required: true
  /contract/toggle_queriability:
    post:
      tags:
        - contract
      summary: sets queriability to true if false and vice versa
      description: ''
      operationId: toggle_queriability
      responses:
        '200':
          description: OK
        '401':
          description: Authorization error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        description: Contract address
        required: true
  /contract/check_queriability:
    post:
      tags:
        - contract
      summary: checks queriability
      description: ''
      operationId: check_queriability
      responses:
        '200':
          description: OK
        '401':
          description: Authorization error
      x-swagger-router-controller: swagger_server.controllers.id_contract_API_functions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        description: Contract address
        required: true
servers:
  - url: 'http://localhost:8000/v0.1'
components:
  schemas:
    Id:
      type: object
      properties:
        id:
          type: string
        db_url:
          type: string
      xml:
        name: Id
    Set:
      type: object
      properties:
        current_id:
          type: string
        new_id:
          type: string
      xml:
        name: Set
    Reset:
      type: object
      properties:
        address:
          type: string
        id:
          type: string
      xml:
        name: Reset
    BulkGetIds:
      type: object
      properties:
        addresses:
          type: array
          items:
            type: string
      xml:
        name: BulkGetIds
    ClaimOwnership:
      type: object
      properties:
        contract_address:
          type: string
        new_owner:
          type: string
      xml:
        name: ClaimOwnership
    Register:
      type: object
      properties:
        contract_address:
          type: string
        user_address:
          type: string
      xml:
        name: Register
    Address:
      type: object
      properties:
        contract_address:
          type: string
      xml:
        name: Address
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []